export default function Historia() {
  return (
    <article>
      <h1>História katedry</h1>
      <p>Aliquam ac ipsum libero. Mauris varius quis mauris ut mattis. Fusce ut ultrices est. Duis dignissim elit sed porttitor sodales. Sed ligula ligula, maximus nec ipsum at, dictum auctor tellus. Mauris rhoncus orci ac lacus tincidunt, nec interdum ligula congue. Vestibulum lacinia turpis a arcu porta fermentum. Fusce vitae vehicula nisl. Vivamus blandit et ligula nec pharetra. Nullam mattis purus at sapien molestie tempor. Morbi suscipit ut dolor id vehicula.</p>

      <p>Suspendisse a diam vestibulum nulla commodo aliquam. Proin eget diam vitae nulla bibendum rutrum ac ac erat. Aliquam eget nunc suscipit, posuere mi id, sodales massa. Nullam maximus quam a dolor interdum aliquet. Maecenas tincidunt efficitur ante, eget fringilla arcu hendrerit non. Duis malesuada porttitor purus, ut suscipit nibh facilisis id. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas ultrices malesuada ipsum, at condimentum justo vehicula vel. Pellentesque libero ligula, tincidunt nec libero sed, tempus rutrum risus. Duis vel cursus ipsum. Nunc rutrum, tellus ac feugiat gravida, lorem libero luctus nibh, vulputate dictum massa risus non mauris. Fusce interdum magna eu est accumsan semper. Pellentesque hendrerit, nunc ut pretium finibus, metus velit egestas elit, eu imperdiet lorem nisl sit amet mauris. Mauris egestas, sapien eget tempor fringilla, ligula enim consectetur tellus, vitae sollicitudin ligula nunc in felis. Sed venenatis leo ac ante interdum eleifend.</p>

      <p>Mauris nec tristique justo. Etiam at magna lectus. Suspendisse tincidunt purus a ex bibendum iaculis. Integer sagittis erat pharetra dignissim cursus. Nulla euismod ex egestas augue sodales consequat. Pellentesque commodo libero lectus, vel aliquam justo ultricies vel. Morbi consectetur magna quis convallis consequat. Pellentesque nec ligula viverra, rhoncus neque id, aliquet nulla. Morbi at ultrices mi, vel condimentum dolor. Donec et bibendum lacus. Donec vel leo quis ex porta porta id eget purus.</p>

      <p>Mauris eleifend sed ligula a sagittis. Duis pellentesque est dolor, ac imperdiet eros luctus sit amet. Vestibulum scelerisque tincidunt libero eu tincidunt. Mauris finibus eu mauris et dictum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi imperdiet vestibulum elit vitae volutpat. Quisque in tempor elit. Nullam sit amet tortor velit. Quisque elit dui, ullamcorper ac feugiat nec, interdum sed magna. Integer pharetra elementum erat, vel condimentum enim ullamcorper fermentum. Phasellus faucibus viverra lobortis. Curabitur non tincidunt ex, at facilisis est. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse mollis auctor erat vel vulputate. Quisque et elit nulla. </p>
    </article>
  );
}   
