import Datum from "@components/datum";
import Separator from "@components/separator";

export default function Media() {
  return (
    <article>
      <h1>V médiách</h1>
      
      <p><a href="http://naucnechodniky.eu/" target="_blank">Náučné chodníky na Slovensku</a><br/>portál s postupne napĺňanou databázou pasportov náučných chodníkov na Slovensku, ktorý vznikol v rámci projektu katedry 
      </p>
      <Separator />
      <p><div className="mb-2"><Datum date={new Date("2020-04-30")} /></div>Spravodajský portál Univerzity Komenského v Bratislave uverejnil rozhovor <a href="https://uniba.sk/spravodajsky-portal/detail-aktuality/back_to_page/univerzita-komenskeho/article/dajme-sa-viest-trasami-naucnych-chodnikov/" target="_blank">Dajme sa viesť trasami náučných chodníkov</a> s RNDr. Ivanom Ružekom, PhD., vedúcim projektu, v rámci ktorého vznikla stránka Naucnechodniky.eu 
      </p><p><div className="mb-2"><Datum date={new Date("2019-05-21")} /></div>V reportáži časopisu Život z 21. 5. 2019 vysvetľujú RNDr. Norbert Polčák, PhD. a doc. RNDr. Milan Trizna, PhD., <a href="https://zivot.pluska.sk/reportaze/krajiny-nam-mizne-voda-preco-slovenske-rieky-priehrady-stracaju-pred-ocami" target="_blank">prečo z krajiny mizne voda a čo s tým</a>
      </p><p><div className="mb-2"><Datum date={new Date("2018-10-08")} /></div>Doc. RNDr. Milan Trizna, PhD., – ako dekan Prírodovedeckej fakulty Univerzity Komenského v Bratislave – vysvetľuje <a href="https://dennikn.sk/1253061/funkcionar-uk-dankovi-by-som-nevyhovel-uz-aj-sem-chodia-ludia-co-chcu-utajit-prace/" target="_blank">v rozhovore</a> Denníka N, prečo vedenie fakulty nemohlo ostať ticho v kauze titulu predsedu parlamentu, a uvádza okolnosti <a href="https://dennikn.sk/1252447/ukazte-svoju-rigoroznu-pracu-vyzyva-danka-prirodovedecka-fakulta/?ref=list" target="_blank">vyhlásenia fakulty</a> (včítane jeho textu), ktorým ho vyzvali ukázať retroaktívne utajenú rigoróznu prácu
      </p><p><div className="mb-2"><Datum date={new Date("2018-06-29")} /></div><a href="http://slovensko.rtvs.sk/relacie/167909/dunaj-kedysi-a-dnes" target="_blank">Dunaj kedysi a dnes</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>v päťdielnom miniseriáli Rádia Slovensko začujete o. i. odborníkov z rôznych oblastí aj doc. Ing. Petra Pišúta, PhD., znalca historického Dunaja
      </p><p><div className="mb-2"><Datum date={new Date("2018-01-03")} /></div>Hosťom <a href="http://www.rtvs.sk/radio/archiv/11436/875841" target="_blank">Nočnej pyramídy</a> Rádia Slovensko – nočnej talkshow so zaujímavými hosťami – bol prof. RNDr. Jozef Minár, CSc., fyzický geograf, člen špičkového tímu Geodynamického vývoja Západných Karpát (1:42 h, začiatok od 1:45 min)
      </p><p><div className="mb-2"><Datum date={new Date("2017-03-20")} /></div><a href="https://fns.uniba.sk/fileadmin/prif/geog/kfg/O_katedre/KovacEtAl2017TimVyskumuGeodynamickeho.pdf" target="_blank">Tím výskumu geodynamického vývoja Západných Karpát</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>článok v Našej univerzite na str. 16-17 o náplni výskumu špičkového vysokoškolského vedeckého tímu Geodynamics, ktorého členmi sú aj naši pracovníci
      </p><p><div className="mb-2"><Datum date={new Date("2017-03-04")} /></div><a href="https://www.youtube.com/watch?v=kEXlfW754Bk" target="_blank">Geografia a geoekológia pre krajinné plánovanie</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>videopozvánka na štúdium na našej katedre na YouTube 
      </p><p><div className="mb-2"><Datum date={new Date("2017-01-12")} /></div><a href="https://dennikn.sk/654404/tuha-zima-bol-rok-ked-sa-v-bratislave-cez-zamrznuty-dunaj-chodilo-dva-mesiace-v-kuse/" target="_blank">Tuhá zima? Bol rok, keď bol Dunaj zamrznutý dva mesiace v kuse a mrzlo aj v marci</a>, reportáž Denníka N, a <a href="http://nun.sk/zima_historia.htm" target="_blank">Z histórie zím v Európe (1500 – 2015)</a>, článok na portáli NUN-Fórum pre vedu a umenie<span className="border-l-2 border-k-green mx-3 py-0.5"></span>dve popularizácie našej publikácie MELO, M., PIŠÚT, P., MATEČNÝ, I. &amp; VIGLAŠ, P.: Johann Ignaz von Felbiger and his meteorological observations in Bratislava in the period 1783-85. In: <em>Meteorologische Zeitschrift</em>. 2016, Vol. 25, No. 1, s. 97-115. ISSN  0941-2948
      </p><p><div className="mb-2"><Datum date={new Date("2016-10-29")} /></div><a href="https://www.youtube.com/watch?v=r1dNrns9CFc" target="_blank">Revitalizácia Karloveského ramena Dunaja</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>video o technických úpravách ramena na YouTube s odborným výkladom Ing. Petra Pišúta, PhD., 1:08 až 8:17 a 26:43 až 27:10
      </p><p><div className="mb-2"><Datum date={new Date("2016-07-21")} /></div><a href="https://slovensko.rtvs.sk/clanky/spolocnost/111858/najteplejsie-miesta-sveta" target="_blank">Najteplejšie miesta sveta</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>relácia s RNDr. Norbertom Polčákom, PhD., na RTVS, Rádio Slovensko
      </p><p><div className="mb-2"><Datum date={new Date("2015-05-30")} /></div><a href="http://pivnicka.pravda.sk/magazin/dobra-poloha-najlepsie-eliminuje-mrazy/394227-clanok.html" target="_blank">Dobrá poloha najlepšie eliminuje mrazy</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>interview s RNDr. Norbertom Polčákom, PhD. a RNDr. Igorom Matečným, PhD. na portáli Varecha.pravda.sk
      </p><p><div className="mb-2"><Datum date={new Date("2015-09-16")} /></div>Hosťom <a href="https://www.rtvs.sk/radio/archiv/11436/301379" target="_blank">Nočnej pyramídy</a> Rádia Slovensko – nočnej talkshow so zaujímavými hosťami – bol meteorológ a geograf RNDr. Norbert Polčák, PhD. (1:40 h)
      </p><p><div className="mb-2"><Datum date={new Date("2015-05-20")} /></div><a href="https://varecha.pravda.sk/vino/digitalne-mapy-spresnuju-suradnice-terroiru/355760-clanok.html" target="_blank">Digitálne mapy spresňujú súradnice terroiru</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>rozhovor s RNDr. Igorom Matečným, PhD., na portáli Varecha.pravda.sk
      </p><p><div className="mb-2"><Datum date={new Date("2014-01-15")} /></div>Hosťom <a href="https://www.rtvs.sk/radio/archiv/11436/103799" target="_blank">Nočnej pyramídy</a> Rádia Slovensko – nočnej talkshow so zaujímavými hosťami – bol dekan Prírodovedeckej fakulty UK v Bratislave a náš kolega, doc. RNDr. Milan Trizna, PhD. (1:40 h)
      </p><p><div className="mb-2"><Datum date={new Date("2011-11-28")} /></div><a href="/pracoviska/geograficka-sekcia/kfggi/kfg/o-katedre/spektrum-vedy/" target="_blank">Spektrum vedy: Späť k prípadu Klimatické zmeny</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>11. časť cyklu televíznych dokumentov o práci a úspechoch slovenských vedcov, účinkujú o. i. doc. RNDr. Milan Trizna, PhD., a doc. RNDr. Miloš Stankoviansky, CSc.</p>
      
    </article>
  );
} 
