import Datum from "@components/datum";
import Separator from "@components/separator";

export default function Media() {
  return (
    <article>
      <h1>Our researchers in media</h1>
      
      <p><a href="http://naucnechodniky.eu/" target="_blank">Educational trails in Slovakia</a><span className="border-l-2 border-k-brown mx-3 py-0.5"></span>An online database of educational trails in Slovakia containing helpful information about each walk. Originated as a department's project.  </p>
      <Separator />
      <p><div className="mb-2"><Datum date={new Date("2021-12-07")} /></div>RNDr. Ivan Ružek, PhD., in a public television ("RTVS") show <a href="https://www.rtvs.sk/televizia/archiv/17008/298853#464" target="_blank"> "Klub 3"</a> on educational trails in Slovakia and its online database with hosts Marcel Janáček and Katarína Brychtová. </p>
      <p><div className="mb-2"><Datum date={new Date("2021-07-21")} /></div>Walked down hundreds of educational trails, now building its online database: <a href="https://ahojmama.pravda.sk/clanky/prechodil-stovky-naucnych-chodnikov-pise-o-/14542-clanok.html" target="_blank">„More than 420 trip suggestions“</a> <span className="border-l-2 border-k-green mx-3 py-0.5"></span>an interview with RNDr. Ivan Ružek, PhD., for parenting online portal Ahojmama.sk</p>
      <p><div className="mb-2"><Datum date={new Date("2021-07-17")} /></div>Doc. Ing. Peter Pišút, PhD., in a public television ("RTVS") documentary feature, <a href="https://www.rtvs.sk/televizia/archiv/17379/280300#0" target="_blank">Fire and Water</a> – from the series about the curiosities of Bratislava. </p>
      <p><div className="mb-2"><Datum date={new Date("2020-11-15")} /></div>Mgr. Miroslav Kožuch, PhD., <a href="https://fb.watch/49wmpUVeah/" target="_blank">in the news of TV Markíza</a> on the mission of Sentinel 6.</p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2020-04-30")} /></div> An interview for the Comenius University news portal, <a href="https://uniba.sk/spravodajsky-portal/detail-aktuality/back_to_page/univerzita-komenskeho/article/dajme-sa-viest-trasami-naucnych-chodnikov/" target="_blank">Let the educational trails lead us</a>, with RNDr. Ivan Ružek, PhD., a project leader and the administrator of the naucnechodniky.eu online database. </p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2019-05-21")} /></div>RNDr. Norbert Polčák, PhD., and doc. RNDr. Milan Trizna, PhD., for the "Život" magazine on <a href="https://zivot.pluska.sk/reportaze/krajiny-nam-mizne-voda-preco-slovenske-rieky-priehrady-stracaju-pred-ocami" target="_blank">why water goes missing from our landscape and how we should deal with this issue. </a></p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2018-10-08")} /></div>Doc. RNDr. Milan Trizna, PhD., as dean of the Faculty of Natural Sciences at UNIBA, in <a href="https://dennikn.sk/1253061/funkcionar-uk-dankovi-by-som-nevyhovel-uz-aj-sem-chodia-ludia-co-chcu-utajit-prace/" target="_blank">an interview</a> for Denník N on the faculty's declaration regarding the controversy of a rigorous thesis of Andrej Danko, the leader of the Slovak parliament, including the analysis of the <a href="https://dennikn.sk/1252447/ukazte-svoju-rigoroznu-pracu-vyzyva-danka-prirodovedecka-fakulta/?ref=list" target="_blank">declaration</a> itself. </p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2018-06-29")} /></div><a href="http://slovensko.rtvs.sk/relacie/167909/dunaj-kedysi-a-dnes" target="_blank">The Danube River in the past and now</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>In a series by public radio "Slovensko" with doc. Ing. Peter Pišút, PhD.</p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2018-01-03")} /></div>An interview for the public radio "Slovensko" show <a href="http://www.rtvs.sk/radio/archiv/11436/875841" target="_blank">Nočná pyramída</a> with Prof. RNDr. Jozef Minár, CSc., a physical geographer and a member of the scientific team exploring the geodynamics of the Western Carpathians.</p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2017-03-20")} /></div><a href="https://fns.uniba.sk/fileadmin/prif/geog/kfg/O_katedre/KovacEtAl2017TimVyskumuGeodynamickeho.pdf" target="_blank">Exploring the geodynamics of the Western Carpathians</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>An article in the "Naša univerzita" magazine about the goals and achievements of the academic and scientific team "Geodynamics", in which participate also the researchers from our department.</p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2017-03-04")} /></div><a href="https://www.youtube.com/watch?v=kEXlfW754Bk" target="_blank">Geography and geoecology for the landscape planning</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>A video presentation briefly introducing the studies in our department. </p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2017-01-12")} /></div><a href="https://dennikn.sk/654404/tuha-zima-bol-rok-ked-sa-v-bratislave-cez-zamrznuty-dunaj-chodilo-dva-mesiace-v-kuse/" target="_blank">Hard winter? There was a year in which the Danube was frozen for two months and the March temperatures dropped below zero</a>, a Denník N article, and <a href="http://nun.sk/zima_historia.htm" target="_blank">The history of Europe's winters (1500 – 2015)</a>, an article on the NUN-Fórum.<span className="border-l-2 border-k-green mx-3 py-0.5"></span>In these articles for the wide public, we present the findings of our scientific publication: MELO, M., PIŠÚT, P., MATEČNÝ, I. &amp; VIGLAŠ, P.: Johann Ignaz von Felbiger and his meteorological observations in Bratislava in the period 1783-85. In: <em>Meteorologische Zeitschrift</em>. 2016, Vol. 25, No. 1, s. 97-115. ISSN  0941-2948</p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2016-10-29")} /></div><a href="https://www.youtube.com/watch?v=r1dNrns9CFc" target="_blank">The revitalization of the Karloveské rameno river channel</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>A video on the technical modifications of the river channel with the commentary of Ing. Peter Pišút, PhD.</p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2016-07-21")} /></div><a href="https://slovensko.rtvs.sk/clanky/spolocnost/111858/najteplejsie-miesta-sveta" target="_blank">The hottest locations in the world</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>A public radio "Slovensko" show with RNDr. Norbert Polčák, PhD.</p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2015-09-16")} /></div>An interview for the public radio "Slovensko" show <a href="https://www.rtvs.sk/radio/archiv/11436/301379" target="_blank">Nočná pyramída</a> with RNDr. Norbert Polčák, PhD., a geographer and meteorologist.</p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2014-01-15")} /></div>An interview for the public radio "Slovensko" show <a href="https://www.rtvs.sk/radio/archiv/11436/103799" target="_blank">Nočná pyramída</a> with doc. RNDr. Milan Trizna, PhD., dean of the Faculty of Natural Sciences at UNIBA.</p>
      <p><div className="mb-2 pt-4"><Datum date={new Date("2011-11-28")} /></div><a href="https://fns.uniba.sk/pracoviska/geograficka-sekcia/kfggi/kfg/o-katedre/spektrum-vedy/" target="_blank">Back to the issue of climate change</a><span className="border-l-2 border-k-green mx-3 py-0.5"></span>A TV documentary show about the work and achievements of Slovak scientists with doc. RNDr. Milan Trizna, PhD., and doc. RNDr. Miloš Stankoviansky, CSc.</p>
      
    </article>
  );
} 
